### ISSUE TITLE
Environment variables for pkg-config override

### ISSUE THREAD

**Issue by sdroege** [gdesmott/metadeps#1]
There should be a common pattern for these so that one can set `CFLAGS`, `LIBS`, `LDFLAGS` for each dependency individually so that `pkg-config` is not called. I would suggest `METADEPS_${DEPENDENCY_NAME}_CFLAGS`, etc.

**Comment by gdesmott** [comment]
Here are the variables currently defined by `pkg-config`:
- `rustc-link-search=native` : `-L` flag
- `rustc-link-search=framework`: `-F` flag
- `rustc-link-lib=static` or `rustc-link-lib` : `-l` flag
- `rustc-link-lib=framework`: `-framework` flag

`metadata` also defines `cargo:include` from the `-I` flag

Shouldn't we have one env variable for each of those rather than `CFLAGS`, `LIBS` and `LDFLAGS`?

If one var is defined for a dep, does it short-circuit `pkg-config` completely or should we still use it to fetch the other values?

**Comment by sdroege** [comment]
> Shouldn't we have one env variable for each of those rather than `CFLAGS`, `LIBS` and `LDFLAGS`?

That would make sense, yes. Naming you can probably take from rustc :)

-F/-L and -l/-framework are the same thing though, just that the framework stuff is for "think different" Apple. I think pkg-config handles them the same too?

> If one var is defined for a dep, does it short-circuit `pkg-config` completely or should we still use it to fetch the other values?

Fetch the ones not provided, I guess.

**Comment by gdesmott** [comment]
> -F/-L and -l/-framework are the same thing though, just that the framework stuff is for "think different" Apple. I think pkg-config handles them the same too?

They are in the `--libs` and `--cflags` section indeed.

But I think it makes sense to keep things expliciti and have a `METADEPS_$DEP_SEARCH_FRAMEWORK` rather than `METADEPS_$DEP_CFLAGS` with metadeps trying to guess if this is a `native` or `framework` dep.

**Comment by gdesmott** [comment]
> Fetch the ones not provided, I guess.

So that means we'll still fail if no `.pc` file is provided. Or maybe we should have a `METADEPS_$DEP_NO_PKGCONFIG` to turn it off completely?

**Comment by sdroege** [comment]
> So that means we'll still fail if no `.pc` file is provided. Or maybe we should have a `METADEPS_$DEP_NO_PKGCONFIG` to turn it off completely?

Makes sense

> But I think it makes sense to keep things expliciti and have a `METADEPS_$DEP_SEARCH_FRAMEWORK` rather than `METADEPS_$DEP_CFLAGS` with metadeps trying to guess if this is a `native` or `framework` dep.

The problem with that is that I expect it to confuse users and crate authors. Almost nobody knows this silly Apple specific difference :) But whatever you think makes more sense, no strong opinion here. Whoever sets those environment variables will have to know stuff.

**Comment by gdesmott** [comment]
Here is what I have so far (top and 3rd commit): https://github.com/gdesmott/metadeps/commits/env-vars

Can you please check if that matches what you had in mind?

**Comment by sdroege** [comment]
Looks good to me apart from the two comments I added to the commits

**Comment by gdesmott** [comment]
Fixed in my `wip` branch. Thanks for your input!
